export const cardsPortfolioArray = [
  {id: 1, title: 'WEB UX/UI',
    picture: [
      { imgUrl: 'assets/webPic/dobrodim.svg', alt:'Dobrodim', link: 'https://www.figma.com/file/nlSscuNbndymxBbXcumxLH/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F?node-id=1-55&t=aDzvgIvKE6YDmN2v-0'},
      { imgUrl: 'assets/webPic/goose.svg', alt:'БандероГусь', link: 'https://www.figma.com/proto/WtUzJ7Dq9Gs1Gk9EjhRaBB/UX%2FUI--day-3?node-id=0-373&scaling=scale-down&page-id=0%3A1&starting-point-node-id=4%3A5044&show-proto-sidebar=1'},
      { imgUrl: 'assets/webPic/tamper.svg', alt:'Tamper', link: 'https://tamper.com.ua/'},
      { imgUrl: 'assets/webPic/tapeElectrical.svg', alt:'Ізолента', link: 'https://www.figma.com/proto/ZpHakXradPZCJyPzwoo8j6/%D0%98%D0%97%D0%9E%D0%9B%D0%95%D0%9D%D0%A2%D0%90?node-id=53-21&scaling=scale-down&page-id=0%3A1'},
      { imgUrl: 'assets/webPic/cryptoCat.svg', alt:'Крипто Кіт', link: 'https://www.figma.com/file/f1ocq1MLO7KqxiEb9Y4I8G/%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%BA%D0%BE%D1%82%D1%8B?node-id=0-1&t=PZMunIDi56pKcNXy-0'},
      { imgUrl: '', alt:'', link: ''},
      { imgUrl: '', alt:'', link: ''},
      { imgUrl: '', alt:'', link: ''},
      { imgUrl: '', alt:'', link: ''},
      { imgUrl: '', alt:'', link: ''},
      { imgUrl: '', alt:'', link: ''},
      { imgUrl: '', alt:'', link: ''},
    ],
    active: false
  },
  {id: 2, title: 'LOGO', picture: ['text', 'no text'], active: false},
  {id: 3, title: 'POLYGRAPHY', picture: ['text', 'no text'], active: false},
  {id: 4, title: 'Visual for social networks', picture: ['text', 'no text'], active: false},
  {id: 5, title: 'outdoor decoration', picture: ['text', 'no text'], active: false},
  {id: 6, title: 'souvenirs prints and other', picture: ['text', 'no text'], active: false},
  {id: 7, title: 'board games, stands, Packaging', picture: ['text', 'no text'], active: false},
  {id: 8, title: 'MY ART', picture: ['text', 'no text'], active: true},
]
